version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "0.0.0.0:3141:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata: